### ISSUE TITLE
[help]Confi file for multi session appium 

### ISSUE THREAD

**Issue by RollerIn** [amiya-pattnaik/webdriverIO-with-mochaBDD#10]
Hello Sir,
can you share config for parallel testing for the below requirement?
1. Run tests on multi emulators <android platform>
2. Run tests on multi simulators <iOS platform>
3. Run tests few on android and few on iOS platform
4. Run tests few on desktop and few on android platform

it would be great appreciable if you share the configuration.

Thanks In Advance

**Comment by amiya-pattnaik** [comment]
Hi,
The boilerplate repo is updated to V8. Please check and let me know. So far multi emulators Appium is concerned, the  Appium does not support parallel execution.
