### ISSUE TITLE
Update to WebdriverIO v8

### ISSUE THREAD

**Issue by christian-bromann** [amiya-pattnaik/webdriverIO-with-mochaBDD#11]
Hey 👋 

Thanks for providing this boilerplate project. It seems like it uses WebdriverIO v6 or older which are versions that the WebdriverIO team has deprecated. Please update the dependencies as we otherwise have to remove it [from our docs](https://webdriver.io/docs/boilerplates).

Let me know if you have any questions! Thank you!

**Comment by amiya-pattnaik** [comment]
Hi,
The boilerplate repo is updated to V8. Please check and let me know.
