### ISSUE TITLE
Cant run on Safari local browser

### ISSUE THREAD

**Issue by mirza-ae** [amiya-pattnaik/webdriverIO-with-mochaBDD#3]
Hello,

Every time I attempt to run on an Safari local browser using the Selenium stand alone service, I get the following errors:

[safari #0-0] 1) navigating to contact-us page should allow user to navigating contact-us page 
[safari #0-0] The command 'GET /session/7F688BA9-7F4F-4F89-B4A1-4C839A36A0F2/element/node-7C11BF90-559F-41D3-9419-881D8803648B/displayed' was not found.

The log is below:

"spec" Reporter:
------------------------------------------------------------------
[safari #0-1] Spec: /Users/userx/Workspace/JS/wdio-with-mocha/test/specs/ta-user-login.spec.js
[safari #0-1] Running: safari
[safari #0-1]
[safari #0-1] phptravels.net login page
[safari #0-1]    ✖ should allow user to login 
[safari #0-1]
[safari #0-1] 1 failing (4.6s)
[safari #0-1]
[safari #0-1] 1) phptravels.net login page should allow user to login 
[safari #0-1] The command 'GET /session/152EB8FA-CCE4-47EF-966E-A508E682563C/element/node-20684CDF-3AD3-40E2-8C5D-CACDD1D2A6D6/displayed' was not found.
[safari #0-1] unknown command: The command 'GET /session/152EB8FA-CCE4-47EF-966E-A508E682563C/element/node-20684CDF-3AD3-40E2-8C5D-CACDD1D2A6D6/displayed' was not found.
[safari #0-1]     at getErrorFromResponseBody (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/webdriver/build/utils.js:343:10)
[safari #0-1]     at Request._callback (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/webdriver/build/request.js:121:64)
[safari #0-1]     at Request.self.callback (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/request/request.js:185:22)
[safari #0-1]     at Request.<anonymous> (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/request/request.js:1161:10)
[safari #0-1]     at IncomingMessage.<anonymous> (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/request/request.js:1083:12)
[safari #0-1]     at endReadableNT (_stream_readable.js:1101:12)
[safari #0-1]     at <anonymous>
[safari #0-1]     at Element.isDisplayed (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/webdriverio/build/commands/element/isDisplayed.js:57:38)
[safari #0-1]     at LoginPage.isDisplayed [as waitForloginPageToLoad] (/Users/userx/Workspace/JS/wdio-with-mocha/test/pageobjects/ta-login.page.js:27:28)
[safari #0-1]     at LoginPage.waitForloginPageToLoad [as login] (/Users/userx/Workspace/JS/wdio-with-mocha/test/pageobjects/ta-login.page.js:33:12)
[safari #0-1]     at Context.login (/Users/userx/Workspace/JS/wdio-with-mocha/test/specs/ta-user-login.spec.js:11:15)
------------------------------------------------------------------
[safari #0-0] Spec: /Users/userx/Workspace/JS/wdio-with-mocha/test/specs/ta-contact-us.spec.js
[safari #0-0] Running: safari
[safari #0-0]
[safari #0-0] navigating to contact-us page
[safari #0-0]    ✖ should allow user to navigating contact-us page 
[safari #0-0]
[safari #0-0] 1 failing (6.5s)
[safari #0-0]
[safari #0-0] 1) navigating to contact-us page should allow user to navigating contact-us page 
[safari #0-0] The command 'GET /session/7F688BA9-7F4F-4F89-B4A1-4C839A36A0F2/element/node-7C11BF90-559F-41D3-9419-881D8803648B/displayed' was not found.
[safari #0-0] unknown command: The command 'GET /session/7F688BA9-7F4F-4F89-B4A1-4C839A36A0F2/element/node-7C11BF90-559F-41D3-9419-881D8803648B/displayed' was not found.
[safari #0-0]     at getErrorFromResponseBody (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/webdriver/build/utils.js:343:10)
[safari #0-0]     at Request._callback (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/webdriver/build/request.js:121:64)
[safari #0-0]     at Request.self.callback (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/request/request.js:185:22)
[safari #0-0]     at Request.<anonymous> (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/request/request.js:1161:10)
[safari #0-0]     at IncomingMessage.<anonymous> (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/request/request.js:1083:12)
[safari #0-0]     at endReadableNT (_stream_readable.js:1101:12)
[safari #0-0]     at <anonymous>
[safari #0-0]     at Element.isDisplayed (/Users/userx/Workspace/JS/wdio-with-mocha/node_modules/webdriverio/build/commands/element/isDisplayed.js:57:38)
[safari #0-0]     at ContactUS.isDisplayed [as waitForContactPageToLoad] (/Users/userx/Workspace/JS/wdio-with-mocha/test/pageobjects/ta-contactus.page.js:21:30)
[safari #0-0]     at Context.waitForContactPageToLoad (/Users/userx/Workspace/JS/wdio-with-mocha/test/specs/ta-contact-us.spec.js:12:15)

Stdout:
2019-03-05T21:47:37.237Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
**** let's go ****
2019-03-05T21:47:37.299Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-03-05T21:47:38.499Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./test/config/suite.mocha.conf.js
2019-03-05T21:47:38.509Z INFO @wdio/local-runner: Start worker 0-1 with arg: ./test/config/suite.mocha.conf.js
2019-03-05T21:47:51.642Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code 1
2019-03-05T21:47:59.474Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1

 RUNNING  0-0 in safari - /test/specs/ta-contact-us.spec.js
 RUNNING  0-1 in safari - /test/specs/ta-user-login.spec.js

Stdout:
2019-03-05T21:48:04.151Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
**** let's go ****
2019-03-05T21:48:04.216Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-03-05T21:48:05.472Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./test/config/suite.mocha.conf.js
2019-03-05T21:48:05.482Z INFO @wdio/local-runner: Start worker 0-1 with arg: ./test/config/suite.mocha.conf.js

Test Suites:     0 passed, 2 total (0% completed)
Time:            🕕  21.35s

Ending WebDriver sessions gracefully ...
(press ctrl+c again to hard kill the runner)

Ending WebDriver sessions gracefully ...

Stdout:
2019-03-05T21:48:04.151Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
**** let's go ****
2019-03-05T21:48:04.216Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-03-05T21:48:05.472Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./test/config/suite.mocha.conf.js
2019-03-05T21:48:05.482Z INFO @wdio/local-runner: Start worker 0-1 with arg: ./test/config/suite.mocha.conf.js
2019-03-05T21:48:25.500Z INFO @wdio/local-runner: Shutting down spawned worker
2019-03-05T21:48:25.526Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code null
2019-03-05T21:48:25.527Z INFO @wdio/cli:Launcher: Run onComplete hook
**** that's it ****

Test Suites:     0 passed, 1 failed, 2 total (50% completed)
Time:            🕖  21.39s

npm ERR! Test failed.  See above for more details.

@amiya-pattnaik Can you please look into this issue?

**Comment by amiya-pattnaik** [comment]
It is nothing to do with the project or  webdriverio.
The issue is with Safari Driver, Make sure you required set up for Safari. Contact Apple for Safari related issue.
