### ISSUE TITLE
Can't we move wdio config files to ES6?

### ISSUE THREAD

**Issue by shridharkalagi** [amiya-pattnaik/webdriverIO-with-mochaBDD#6]
Can't we move wdio config files to ES6?

**Comment by amiya-pattnaik** [comment]
didn't get what you want / requirement. Can you give more details on what you want to do it ?

**Comment by shridharkalagi** [comment]
Can we move the wdio config file [here](https://github.com/amiya-pattnaik/webdriverIO-with-mochaBDD/blob/master/test/config/suite.appium.conf.js) to ES6 syntax. I have a couple of config files to maintain and it would be easy for me if they are in ES6

**Comment by amiya-pattnaik** [comment]
wdio config file is just a JSON Object with key and value pair like any other javascript object.
It is nothing to do anything thing special with ES6 Syntax.

**Comment by shridharkalagi** [comment]
Not necessarily. Please see my config file [here](https://github.com/shridharkalagi/Wdio/blob/master/configs/wdio.local.conf.js) Can I move this to ES6 syntax with import statements?
